require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'Marlin' do
  use_expo_modules!
  use_modular_headers!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
# @generated begin @maplibre/maplibre-react-native:post-install - expo prebuild (DO NOT MODIFY) sync-6e76c80af0d70c0003d06822dd59b7c729fca472
    $MLRN.post_install(installer)
# @generated end @maplibre/maplibre-react-native:post-install
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

  pods_root = installer.sandbox.root

  #
  # 1) React-jsitooling.modulemap – delete duplicate public modulemap
  #
  jsitooling_public = File.join(
    pods_root,
    "Headers/Public/react_runtime/React-jsitooling.modulemap"
  )
  File.delete(jsitooling_public) if File.exist?(jsitooling_public)

  #
  # 2) Remove -fmodule-map-file references to that deleted file
  #
  Dir.glob(File.join(pods_root, "Target Support Files", "**", "*.xcconfig")).each do |xcconfig_path|
    next unless File.exist?(xcconfig_path)

    content = File.read(xcconfig_path)
    cleaned = content.gsub(
      /\s*-fmodule-map-file="\$\{PODS_ROOT\}\/Headers\/Public\/react_runtime\/React-jsitooling\.modulemap"/,
      ""
    )

    File.write(xcconfig_path, cleaned) if cleaned != content
  end

  #
  # 3) Tidy React-RuntimeCore.modulemap (avoid module name clashes)
  #
  runtime_core_modulemap = File.join(
    pods_root,
    "Target Support Files",
    "React-RuntimeCore",
    "React-RuntimeCore.modulemap"
  )

  if File.exist?(runtime_core_modulemap)
    content = File.read(runtime_core_modulemap)
    # give it a unique name instead of reusing `react_runtime`
    content = content.sub("module react_runtime", "module React_RuntimeCore")
    # remove wildcard submodule that causes conflicts
    content = content.gsub(/module \* \{ export \* \}/, "")
    File.write(runtime_core_modulemap, content)
  end

  #
  # 4) Tidy React-RuntimeHermes.modulemap (same wildcard issue)
  #
  runtime_hermes_modulemap = File.join(
    pods_root,
    "Target Support Files",
    "React-RuntimeHermes",
    "React-RuntimeHermes.modulemap"
  )

  if File.exist?(runtime_hermes_modulemap)
    content = File.read(runtime_hermes_modulemap)
    content = content.gsub(/module \* \{ export \* \}/, "")
    File.write(runtime_hermes_modulemap, content)
  end

  #
  # 5) React-jsitooling.modulemap in Target Support Files – rename module
  #
  jsitooling_modulemap = File.join(
    pods_root,
    "Target Support Files",
    "React-jsitooling",
    "React-jsitooling.modulemap"
  )

  if File.exist?(jsitooling_modulemap)
    content = File.read(jsitooling_modulemap)
    content = content.sub("module react_runtime", "module React_jsitooling")
    content = content.gsub(/module \* \{ export \* \}/, "")
    File.write(jsitooling_modulemap, content)
  end

  #
  # 6) React-RuntimeApple.modulemap – same duplicate-module issue under ReactCommon
  #
  runtime_apple_public = File.join(
    pods_root,
    "Headers/Public/ReactCommon/React-RuntimeApple.modulemap"
  )
  File.delete(runtime_apple_public) if File.exist?(runtime_apple_public)

  Dir.glob(File.join(pods_root, "Target Support Files", "**", "*.xcconfig")).each do |xcconfig_path|
    next unless File.exist?(xcconfig_path)

    content = File.read(xcconfig_path)
    cleaned = content.gsub(
      /\s*-fmodule-map-file="\$\{PODS_ROOT\}\/Headers\/Public\/ReactCommon\/React-RuntimeApple\.modulemap"/,
      ""
    )

    File.write(xcconfig_path, cleaned) if cleaned != content
  end

  #
  # 7) Normalise duplicated "-Xcc -Xcc" flags that Xcode 16+ hates
  #
  Dir.glob(File.join(pods_root, "Target Support Files", "**", "*.xcconfig")).each do |xcconfig_path|
    next unless File.exist?(xcconfig_path)

    content = File.read(xcconfig_path)
    cleaned = content.gsub("-Xcc -Xcc ", "-Xcc ")
    File.write(xcconfig_path, cleaned) if cleaned != content
  end
end
end
