default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight (Internal Testing)"
  lane :testflight_internal do
    ENV['APP_MODE'] = 'test'

    setup_ci if ENV['CI']

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['APP_STORE_CONNECT_API_KEY_ID']}.p8"),
      in_house: false
    )

    match(
      type: "appstore",
      readonly: false,
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      api_key: api_key
    )

    cocoapods(
      clean_install: true
    )

    gym(
      scheme: "Marlin",
      workspace: "Marlin.xcworkspace",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "Marlin.ipa",
      verbose: true,
      suppress_xcode_output: false,
      xcargs: "-verbose",
      buildlog_path: "./build/logs"
    )

    pilot(
      skip_waiting_for_build_processing: true,
      app_identifier: "com.marlin.live",
      ipa: "./build/Marlin.ipa",
      distribute_external: false,
      groups: ["Main"],
      api_key: api_key
    )
  end

  desc "Deploy a new version to the App Store"
  lane :app_store do
    ENV['APP_MODE'] = 'prod'

    setup_ci if ENV['CI']

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['APP_STORE_CONNECT_API_KEY_ID']}.p8"),
      in_house: false
    )

    match(
      type: "appstore",
      readonly: false,
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      api_key: api_key
    )

    cocoapods(
      clean_install: true
    )

    gym(
      scheme: "Marlin",
      workspace: "Marlin.xcworkspace",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "Marlin.ipa",
      verbose: true,
      suppress_xcode_output: false,
      xcargs: "-verbose",
      buildlog_path: "./build/logs"
    )

    deliver(
      submit_for_review: false,
      automatic_release: false,
      skip_metadata: false,
      skip_screenshots: false,
      app_identifier: "com.marlin.live",
      ipa: "./build/Marlin.ipa",
      api_key: api_key
    )
  end
end
