name: CI – Build & Deploy Frontend to Release Server

on:
  push:
    branches:
      - release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      DEPLOY_KEY: ${{ secrets.MARLIN_DEPLOY_KEY }}
      DEPLOY_PATH: ${{ secrets.MARLIN_FRONTEND_DEPLOY_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Build frontend
        run: npm run build

      - name: Copy dist to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.MARLIN_DEPLOY_KEY }}
          source: "dist/*"
          target: ${{ env.DEPLOY_PATH }}